module.exports = {
  host: '175.178.115.221',
  user: 'yang',
  password: '88359397',
  database: 'resultSystem',
  table: {
    users: 'admin_user',
    result: 'result',
    student: 'student',
    resultDetail: 'result_detail',
    testTime: 'test_time',
  },
  GRADE_SUBJECT: [
    [],
    [
      'Chinese',
      'Math',
      'English',
      'Politics',
      'History',
      'Biology',
      'Geography',
      'Sport',
      'Total',
    ],
    [
      'Chinese',
      'Math',
      'English',
      'Politics',
      'History',
      'Physical',
      'Biology',
      'Geography',
      'Sport',
      'Total',
    ],
    [
      'Chinese',
      'Math',
      'English',
      'Politics',
      'History',
      'Physical',
      'Chemistry',
      'Composite',
      'Sport',
      'Total',
    ],
  ],
  SUBJECT_TRANSLATE: {
    Chinese: '语文',
    Math: '数学',
    English: '英语',
    Politics: '道法',
    History: '历史',
    Physical: '物理',
    Chemistry: '化学',
    Biology: '生物',
    Geography: '地理',
    Total: '总分',
    Composite: '综合',
    Sport: '体育',
  },
}
