module.exports = {
  host: '175.178.115.221',
  user: 'yang',
  password: '88359397',
  database: 'resultSystem',
  table: {
    users: 'admin_user',
    result: 'result',
    student: 'student',
    resultDetail: 'result_detail',
    testTime: 'test_time'
  },
  GRADE_SUBJECT : [
    [],
    [
      'Chinese',
      'Math',
      'English',
      'Politics',
      'History',
      'Biology',
      'Geography',
      'Sport',
      'Total',
    ],
    [
      'Chinese',
      'Math',
      'English',
      'Politics',
      'History',
      'Physical',
      'Biology',
      'Geography',
      'Sport',
      'Total',
    ],
    [
      'Chinese',
      'Math',
      'English',
      'Politics',
      'History',
      'Physical',
      'Chemistry',
      'Sport',
      'Total',
    ],
  ]
}
