export const GRADE_ONE_SUBJECT = {
    ONE: [
        'Chinese',
        'Math',
        'English',
        'Politics',
        'History',
        'Biology',
        'Geography',
    ],
    TWO: [
        'Chinese',
        'Math',
        'English',
        'Politics',
        'History',
        'Physical',
        'Biology',
        'Geography',
    ],
    THREE: [
        'Chinese',
        'Math',
        'English',
        'Politics',
        'History',
        'Physical',
        'Chemistry',
        'Biology',
        'Geography',
    ],
}

export const SUBJECT_TRANSLATE = {
    Chinese: '语文',
    Math: '数学',
    English: '英语',
    Politics: '道法',
    History: '历史',
    Physical: '物理',
    Chemistry: '化学',
    Biology: '生物',
    Geography: '地理',
    Total: '总分',
    Composite: '综合',
    Sport: '体育',
}
